### model
### huggingface

model_name_or_path: /scratch/network/jj4485/models/Llama-3.2-3B/
model_type: llama
### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: datasets/alpaca_dataset.json
template: alpaca
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Llama-FineTune
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-4
num_train_epochs: 50
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
